### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by vincent-herlemont** [vincent-herlemont/gitplot#9]
To improve the quality of gitplot we have to find a way to test with a real git repository.

# TODO
- [ ] Create script to generate a fake git repository.
- [ ] Choose a test lib for python.
- [ ] Implement integration tests.
